# Generated by Django 4.1.7 on 2023-03-17 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_patient_doctor_patient_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Patient Summary',
                'verbose_name_plural': 'Patients Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.patient',),
        ),
    ]
