# Generated by Django 4.1.7 on 2023-03-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_patientsummary_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_of_appointment',
            field=models.DateTimeField(verbose_name='Date of appointment'),
        ),
    ]
